"""4x4 sudoku data: grid enumeration, geometric symmetry group, orbit split,
puzzle generation with uniqueness check.

Boards are numpy int arrays of shape (16,), row-major. Tokens: 0 = MASK,
1..4 = digits. A "solution" contains only 1..4; a "puzzle" has 0 for blanks.
"""

from __future__ import annotations

import itertools
import json
from pathlib import Path

import numpy as np

MASK = 0
N = 4
CELLS = 16
# The one seed that defines the train/eval orbit split. Training, eval-set
# generation, and the demo must all use it, or eval orbits leak into training.
SPLIT_SEED = 12345

# unit index sets: 4 rows, 4 cols, 4 boxes
ROWS = [tuple(range(r * 4, r * 4 + 4)) for r in range(4)]
COLS = [tuple(range(c, 16, 4)) for c in range(4)]
BOXES = [
    tuple((br * 2 + i) * 4 + bc * 2 + j for i in range(2) for j in range(2))
    for br in range(2)
    for bc in range(2)
]
UNITS = ROWS + COLS + BOXES


def is_valid_solution(board: np.ndarray) -> bool:
    if board.shape != (CELLS,) or not np.all((board >= 1) & (board <= 4)):
        return False
    return all(sorted(board[list(u)]) == [1, 2, 3, 4] for u in UNITS)


def _solve(board: list[int], limit: int) -> list[np.ndarray]:
    """Backtracking solver; returns up to `limit` solutions."""
    out: list[np.ndarray] = []

    def peers_ok(idx: int, v: int) -> bool:
        return all(
            board[j] != v for u in UNITS if idx in u for j in u if j != idx
        )

    def rec() -> bool:
        try:
            idx = board.index(MASK)
        except ValueError:
            out.append(np.array(board))
            return len(out) >= limit
        for v in range(1, 5):
            if peers_ok(idx, v):
                board[idx] = v
                if rec():
                    board[idx] = MASK
                    return True
                board[idx] = MASK
        return False

    rec()
    return out


def all_solutions() -> np.ndarray:
    """All 288 valid 4x4 grids, shape (288, 16), deterministic order."""
    sols = _solve([MASK] * CELLS, limit=10_000)
    assert len(sols) == 288, f"expected 288 grids, got {len(sols)}"
    return np.stack(sols)


def count_solutions(puzzle: np.ndarray, limit: int = 2) -> int:
    return len(_solve(list(puzzle), limit=limit))


# ---------------------------------------------------------------- symmetries
def _perm_from_maps(row_map: list[int], col_map: list[int], transpose: bool) -> tuple[int, ...]:
    """Position permutation p such that transformed[i] = board[p[i]]."""
    p = []
    for r in range(4):
        for c in range(4):
            sr, sc = (c, r) if transpose else (r, c)
            p.append(row_map[sr] * 4 + col_map[sc])
    return tuple(p)


def symmetry_group() -> np.ndarray:
    """All geometric symmetries of 4x4 sudoku as position permutations,
    shape (G, 16). Generated by band swaps, in-band row/col swaps, and
    transpose (no digit relabelling). Includes identity; closed under
    composition (128 elements)."""
    band_row_maps = []
    for bands in itertools.permutations([(0, 1), (2, 3)]):
        for b0 in itertools.permutations(bands[0]):
            for b1 in itertools.permutations(bands[1]):
                band_row_maps.append(list(b0 + b1))
    perms = {
        _perm_from_maps(rm, cm, t)
        for rm in band_row_maps
        for cm in band_row_maps
        for t in (False, True)
    }
    assert len(perms) == 128
    return np.array(sorted(perms))


def orbits(solutions: np.ndarray, group: np.ndarray) -> list[list[int]]:
    """Partition solution indices into orbits under the group."""
    key_to_idx = {sol.tobytes(): i for i, sol in enumerate(solutions)}
    seen: set[int] = set()
    out: list[list[int]] = []
    for i in range(len(solutions)):
        if i in seen:
            continue
        orbit = {key_to_idx[solutions[i][p].tobytes()] for p in group}
        seen |= orbit
        out.append(sorted(orbit))
    return out


def orbit_split(rng: np.random.Generator, eval_fraction: float = 1 / 6) -> tuple[np.ndarray, np.ndarray]:
    """Split the 288 solutions into (train, eval) by whole orbits."""
    sols = all_solutions()
    group = symmetry_group()
    obs = orbits(sols, group)
    order = rng.permutation(len(obs))
    target = int(round(len(sols) * eval_fraction))
    eval_idx: list[int] = []
    for oi in order:
        if len(eval_idx) >= target:
            break
        eval_idx += obs[oi]
    eval_set = set(eval_idx)
    train_idx = [i for i in range(len(sols)) if i not in eval_set]
    return sols[train_idx], sols[sorted(eval_set)]


# ------------------------------------------------------------------- puzzles
def make_puzzle(solution: np.ndarray, n_clues: int, rng: np.random.Generator) -> np.ndarray | None:
    """Remove cells from a solution down to n_clues, keeping uniqueness.
    Returns None if no unique puzzle with exactly n_clues was found."""
    puzzle = solution.copy()
    order = rng.permutation(CELLS)
    for idx in order:
        if int((puzzle != MASK).sum()) <= n_clues:
            break
        old = puzzle[idx]
        puzzle[idx] = MASK
        if count_solutions(puzzle) != 1:
            puzzle[idx] = old
    return puzzle if int((puzzle != MASK).sum()) == n_clues else None


def solved(board: np.ndarray, puzzle: np.ndarray) -> bool:
    """Full, valid, and consistent with the puzzle's clues. For puzzles with a
    unique solution this is equivalent to matching it; it also covers 0-clue
    (empty) boards, where any valid grid counts."""
    clue = puzzle != MASK
    return is_valid_solution(board) and bool(np.all(board[clue] == puzzle[clue]))


def validity_score(board: np.ndarray) -> float:
    """Partial credit in [0, 1]: mean over the 12 units of (distinct non-MASK
    digits) / 4. Equals 1.0 iff the board is a valid full solution."""
    return float(
        np.mean([len(set(board[list(u)]) - {MASK}) / 4 for u in UNITS])
    )


def generate_eval_set(
    path: Path, seed: int = 12345, per_clue: int = 100, clue_counts: tuple[int, ...] = (0, 4, 5, 6, 7, 8)
) -> int:
    """Write a fixed eval set of distinct unique-solution puzzles from
    eval-orbit solutions (the orbit split always uses SPLIT_SEED; `seed` only
    drives puzzle generation). n_clues=0 emits a single empty board (greedy
    eval is deterministic)."""
    rng = np.random.default_rng(seed)
    _, eval_sols = orbit_split(np.random.default_rng(SPLIT_SEED))
    path.parent.mkdir(parents=True, exist_ok=True)
    seen: set[bytes] = set()
    n = 0
    with path.open("w") as f:
        for n_clues in clue_counts:
            if n_clues == 0:
                f.write(json.dumps({"puzzle": [0] * CELLS, "solution": None, "n_clues": 0}) + "\n")
                n += 1
                continue
            made = 0
            attempts = 0
            while made < per_clue and attempts < per_clue * 50:
                attempts += 1
                sol = eval_sols[rng.integers(len(eval_sols))]
                puz = make_puzzle(sol, n_clues, rng)
                if puz is None or puz.tobytes() in seen:
                    continue
                seen.add(puz.tobytes())
                f.write(
                    json.dumps({"puzzle": puz.tolist(), "solution": sol.tolist(), "n_clues": n_clues}) + "\n"
                )
                made += 1
                n += 1
    return n


def load_eval_set(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line]
